/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DeliveryManRole;

import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;
import Business.Menu.Menu;
import Business.Orders.Order;
import Business.Restaurant.Restaurant;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class DeliveryManWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount userAccount;
    String deliveryManName;
    Order order;
    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    
    public DeliveryManWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.system = business;
        this.deliveryManName = userAccount.getUsername();
        
        populateTable();
        DeliveryMan dm = system.getDeliveryManDirectory().findDeliveryMan(userAccount.getUsername());
        jLabel1.setText(String.valueOf(dm.getRatings()));
    }
    
    public void populateTable(){
        
        DefaultTableModel dtm = (DefaultTableModel) deliveryTable.getModel();
        dtm.setRowCount(0);
        
                 
        for(Order o : system.getOrderHistory().getOrderHisotry()){
            if(o.getDeliveryMan()!=null){
                if(o.getDeliveryMan().getDeliveryManName().equals(deliveryManName)){
                    Object row[] = new Object[6];
                    row[0] = o.getOrderID();
                    row[1] = o.getRestaurant().getName();
                    row[2] = o.getUserAccount().getUsername();
                    row[3] = o;
                    row[4] = o.getComments();
                    row[5] = o.getAmount();
                   // row[6] = 
                    dtm.addRow(row);
                }
            }else{
                System.out.println("Orders not found");
            }
        } 
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        assignJButton = new javax.swing.JButton();
        refreshJButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        deliveryTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        assignJButton.setText("Assign to me");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });
        add(assignJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 130, 50));

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 40, -1, -1));

        deliveryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Restaurant Name", "Customer Name", "Order Status", "Comments", "Total Value"
            }
        ));
        jScrollPane2.setViewportView(deliveryTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 90, 720, 140));

        jLabel1.setText("<<Ratings>>");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 110, -1));

        jLabel2.setText("Ratings");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 50, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Order Details");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 190, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed

//        int selectedRow = workRequestJTable.getSelectedRow();
//        
//        if (selectedRow < 0){
//            return;
//        }
//        
//        WorkRequest request = (WorkRequest)workRequestJTable.getValueAt(selectedRow, 0);
//        request.setReceiver(userAccount);
//        request.setStatus("Pending");
        
        System.out.println("DDD ");
        int selectedRow1 = deliveryTable.getSelectedRow();
        if(selectedRow1 < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
        }
        order = (Order)deliveryTable.getValueAt(selectedRow1,3);
        System.out.println("Order "+ order.getOrderStatus());
        order.setOrderStatus("On the way");
              
        
        populateTable();
        
        
        
        
    }//GEN-LAST:event_assignJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        populateTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignJButton;
    private javax.swing.JTable deliveryTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refreshJButton;
    // End of variables declaration//GEN-END:variables
}
